version: "3.9"

services:
   api:
      build:
         context: .
         dockerfile: Dockerfile.dev
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
         - .:/app
      ports:
         - 8000:8000
      env_file:
         - .env
      restart: "on-failure"
      depends_on:
         - postgres-db
      networks:
         - hospital-api

   postgres-db:
      image: kartoza/postgis:12.0
      ports:
         - 5432:5432
      volumes:
         - postgres_data:/var/lib/postgresql
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASS=${POSTGRES_PASS}
         - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      restart: "on-failure"
      networks:
         - hospital-api
   redis:
      container_name: "redis"
      image: "redis:alpine"
      command: redis-server /usr/local/etc/redis/redis.conf --requirepass  admin123456
      ports:
         - 6379:6379
      volumes:
         - .redis.conf:/usr/local/etc/redis/redis.conf


   nginx:
      restart: always
      depends_on:
         - api
      build:
         context: ./nginx
         dockerfile: Dockerfile.dev
      ports:
         - 8080:80
      networks:
         - hospital-api
   

networks:
   hospital-api:
      driver: bridge

volumes:
   postgres_data: